image: maven:3-jdk-8
variables:
  DOCKER_DRIVER: overlay
  SPRING_PROFILES_ACTIVE: gitlab-ci

stages:
  - jib

maven:
  image: maven:3-jdk-8
  stage: maven
  script: "mvn clean install"

build:
  image: maven:3-jdk-8
  stage: jib
  script:
    - "mvn install"
    - "cd reboarding-microservices"
    - "mvn jib:build"