image: docker:latest
services:
  - docker:dind
  
variables:
  DOCKER_DRIVER: overlay
  SPRING_PROFILES_ACTIVE: gitlab-ci

  
stages:
  - maven
  - build
  - deploy

maven:
  image: maven:3-jdk-8
  stage: maven
  script: "mvn clean install"

build:
  stage: build
  script:
    - "docker-compose build"

deploy:
  stage: deploy
  script:
    - "docker-compose push"
    - "docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com"