image: maven:latest
cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - .m2
    - ./domain
    - ./http-commons
    - ./reboarding-microservices
    - ./client
    

variables:
  SPRING_PROFILES_ACTIVE: gitlab-ci
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

stages:
  - validate
  - compile
  - test
  - package
  - verify
  - install
  - deploy


validate:
  stage: validate
  script: "mvn validate"

compile:
  stage: compile
  script: "mvn compile"

test:
  stage: test
  script: "mvn test"

package:
  stage: package
  script: "mvn package"

verify:
  stage: verify
  script: "mvn verify"

install:
  stage: install
  script: "mvn install"

deploy:
  stage: deploy
  script: "mvn jib:build -Djib.to.auth.username=$CI_REGISTRY_USER -Djib.to.auth.password=$CI_REGISTRY_PASSWORD"

# kubernetes config generation is still missing
# skaffold render -p qa --output='k8s/qa.yaml'