image: maven:3-jdk-8
variables:
  DOCKER_DRIVER: overlay
  SPRING_PROFILES_ACTIVE: gitlab-ci

stages:
  - maven
  - jib

maven:
  image: maven:3-jdk-8
  stage: maven
  script: "mvn clean install"

build:
  extends: maven
  stage: jib
  script:
    - "mvn install"
    - "cd reboarding-microservices"
    - "mvn jib:build -Djib.to.auth.username=$CI_REGISTRY_USER -Djib.to.auth.password=$CI_REGISTRY_PASSWORD"