apiVersion: v1
kind: Service
metadata:
  name: api-gateway
spec:
  selector:
    app: api-gateway
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api-gateway
  name: api-gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: bombie/reboarding:api-gateway
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: registration-service
spec:
  selector:
    app: registration-service
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: registration-service
  name: registration-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: registration-service
  template:
    metadata:
      labels:
        app: registration-service
    spec:
      containers:
        - name: registration-service
          image: bombie/reboarding:registration-service
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: status-service
spec:
  selector:
    app: status-service
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: status-service
  name: status-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: status-service
  template:
    metadata:
      labels:
        app: status-service
    spec:
      containers:
        - name: status-service
          image: bombie/reboarding:status-service
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: entry-service
spec:
  selector:
    app: entry-service
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: entry-service
  name: entry-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: entry-service
  template:
    metadata:
      labels:
        app: entry-service
    spec:
      containers:
        - name: entry-service
          image: bombie/reboarding:entry-service
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: exit-service
spec:
  selector:
    app: exit-service
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: exit-service
  name: exit-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: exit-service
  template:
    metadata:
      labels:
        app: exit-service
    spec:
      containers:
        - name: exit-service
          image: bombie/reboarding:exit-service
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: entry-request-handler
spec:
  selector:
    app: entry-request-handler
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: entry-request-handler
  name: entry-request-handler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: entry-request-handler
  template:
    metadata:
      labels:
        app: entry-request-handler
    spec:
      containers:
        - name: entry-request-handler
          image: bombie/reboarding:entry-request-handler
          ports:
            - containerPort: 8080
