version: "3.8"
services:
  api-gateway:
    build: ./api-gateway
    image: bombie/reboarding:api-gateway
    ports:
      - "80:8080"
    networks:
      - public-network
      - service-network
    depends_on:
      - registration-service
      - status-service
      - entry-service
      - exit-service
    volumes:
      - basic-volume:/var/lib/service/api-gateway

  registration-service:
    build: ./registration-service
    image: bombie/reboarding:registration-service
    ports:
      - "100:8080"
    networks:
      - service-network
    depends_on:
      - entry-request-handler
    volumes:
      - basic-volume:/var/lib/service/registration-service
  status-service:
    build: ./status-service
    image: bombie/reboarding:status-service
    ports:
      - "101:8080"
    networks:
      - service-network
    depends_on:
      - entry-request-handler
    volumes:
      - basic-volume:/var/lib/service/status-service
  entry-service:
    build: ./entry-service
    image: bombie/reboarding:entry-service
    ports:
      - "102:8080"
    networks:
      - service-network
    depends_on:
      - entry-request-handler
    volumes:
      - basic-volume:/var/lib/service/entry-service
  exit-service:
    build: ./exit-service
    image: bombie/reboarding:exit-service
    ports:
      - "103:8080"
    networks:
      - service-network
    depends_on:
      - entry-request-handler
    volumes:
      - basic-volume:/var/lib/service/exit-service

  entry-request-handler:
    build: ./entry-request-handler
    image: bombie/reboarding:entry-request-handler
    ports:
      - "81:8080"
    networks:
      - service-network
    volumes:
      - basic-volume:/var/lib/service/entry-request-handler

  #module:
  #  build: ./module
  #  image: bombie/reboarding:module
volumes:
  basic-volume:

networks:
  public-network:
    external: true
  service-network:
