apiVersion: skaffold/v2beta5
kind: Config
metadata:
  name: reboarding
build:
  artifacts:
    - image: registry.gitlab.com/bombie/reboarding/api-gateway
      context: .
      jib:
        project: :api-gateway
    - image: registry.gitlab.com/bombie/reboarding/registration-service
      context: .
      jib: 
        project: :registration-service
    - image: registry.gitlab.com/bombie/reboarding/status-service
      context: .
      jib:
        project: :status-service
    - image: registry.gitlab.com/bombie/reboarding/entry-request-handler
      context: .
      jib:
        project: :entry-request-handler

deploy:
  statusCheckDeadlineSeconds: 300
  kustomize:
    paths:
      - kustomize/base

profiles:
  - name: qa
    deploy:
      kustomize:
        paths:
          - kustomize/qa
  - name: test
    deploy:
      kustomize:
        paths:
          - kustomize/test
