apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base

patchesStrategicMerge:
  - update-replicas.yaml
  - use-configmap.yaml
  
configMapGenerator:
  - name: qa-config
    files:
      - application.properties
