apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/managed-by: skaffold-v1.12.0
    skaffold.dev/builder: local
    skaffold.dev/cleanup: "true"
    skaffold.dev/deployer: kustomize
    skaffold.dev/docker-api-version: "1.40"
    skaffold.dev/run-id: f7c22f18-a719-42b1-8a37-c9e58b0edf5a
    skaffold.dev/tag-policy: git-commit
  name: api-gateway
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: api-gateway
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/managed-by: skaffold-v1.12.0
    skaffold.dev/builder: local
    skaffold.dev/cleanup: "true"
    skaffold.dev/deployer: kustomize
    skaffold.dev/docker-api-version: "1.40"
    skaffold.dev/run-id: f7c22f18-a719-42b1-8a37-c9e58b0edf5a
    skaffold.dev/tag-policy: git-commit
  name: entry-request-handler
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: entry-request-handler
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/managed-by: skaffold-v1.12.0
    skaffold.dev/builder: local
    skaffold.dev/cleanup: "true"
    skaffold.dev/deployer: kustomize
    skaffold.dev/docker-api-version: "1.40"
    skaffold.dev/run-id: f7c22f18-a719-42b1-8a37-c9e58b0edf5a
    skaffold.dev/tag-policy: git-commit
  name: entry-service
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: entry-service
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/managed-by: skaffold-v1.12.0
    skaffold.dev/builder: local
    skaffold.dev/cleanup: "true"
    skaffold.dev/deployer: kustomize
    skaffold.dev/docker-api-version: "1.40"
    skaffold.dev/run-id: f7c22f18-a719-42b1-8a37-c9e58b0edf5a
    skaffold.dev/tag-policy: git-commit
  name: exit-service
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: exit-service
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/managed-by: skaffold-v1.12.0
    skaffold.dev/builder: local
    skaffold.dev/cleanup: "true"
    skaffold.dev/deployer: kustomize
    skaffold.dev/docker-api-version: "1.40"
    skaffold.dev/run-id: f7c22f18-a719-42b1-8a37-c9e58b0edf5a
    skaffold.dev/tag-policy: git-commit
  name: registration-service
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: registration-service
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/managed-by: skaffold-v1.12.0
    skaffold.dev/builder: local
    skaffold.dev/cleanup: "true"
    skaffold.dev/deployer: kustomize
    skaffold.dev/docker-api-version: "1.40"
    skaffold.dev/run-id: f7c22f18-a719-42b1-8a37-c9e58b0edf5a
    skaffold.dev/tag-policy: git-commit
  name: status-service
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: status-service
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api-gateway
    app.kubernetes.io/managed-by: skaffold-v1.12.0
    skaffold.dev/builder: local
    skaffold.dev/cleanup: "true"
    skaffold.dev/deployer: kustomize
    skaffold.dev/docker-api-version: "1.40"
    skaffold.dev/run-id: f7c22f18-a719-42b1-8a37-c9e58b0edf5a
    skaffold.dev/tag-policy: git-commit
  name: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
        app.kubernetes.io/managed-by: skaffold-v1.12.0
        skaffold.dev/builder: local
        skaffold.dev/cleanup: "true"
        skaffold.dev/deployer: kustomize
        skaffold.dev/docker-api-version: "1.40"
        skaffold.dev/run-id: f7c22f18-a719-42b1-8a37-c9e58b0edf5a
        skaffold.dev/tag-policy: git-commit
    spec:
      containers:
      - image: registry.gitlab.com/bombie/reboarding:4c5158a4978a6f80219cf410fa56df06e4bb85be296b923e073eee9092137fa9
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        name: api-gateway
        ports:
        - containerPort: 8080
        readinessProbe:
          failureThreshold: 1
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          periodSeconds: 5
        resources:
          limits:
            cpu: 4000m
            memory: 512M
          requests:
            cpu: 1000m
            memory: 256M
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: entry-request-handler
    app.kubernetes.io/managed-by: skaffold-v1.12.0
    skaffold.dev/builder: local
    skaffold.dev/cleanup: "true"
    skaffold.dev/deployer: kustomize
    skaffold.dev/docker-api-version: "1.40"
    skaffold.dev/run-id: f7c22f18-a719-42b1-8a37-c9e58b0edf5a
    skaffold.dev/tag-policy: git-commit
  name: entry-request-handler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: entry-request-handler
  template:
    metadata:
      labels:
        app: entry-request-handler
        app.kubernetes.io/managed-by: skaffold-v1.12.0
        skaffold.dev/builder: local
        skaffold.dev/cleanup: "true"
        skaffold.dev/deployer: kustomize
        skaffold.dev/docker-api-version: "1.40"
        skaffold.dev/run-id: f7c22f18-a719-42b1-8a37-c9e58b0edf5a
        skaffold.dev/tag-policy: git-commit
    spec:
      containers:
      - image: registry.gitlab.com/bombie/reboarding:4c5158a4978a6f80219cf410fa56df06e4bb85be296b923e073eee9092137fa9
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        name: entry-request-handler
        ports:
        - containerPort: 8080
        readinessProbe:
          failureThreshold: 1
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          periodSeconds: 5
        resources:
          limits:
            cpu: 4000m
            memory: 512M
          requests:
            cpu: 1000m
            memory: 256M
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: entry-service
    app.kubernetes.io/managed-by: skaffold-v1.12.0
    skaffold.dev/builder: local
    skaffold.dev/cleanup: "true"
    skaffold.dev/deployer: kustomize
    skaffold.dev/docker-api-version: "1.40"
    skaffold.dev/run-id: f7c22f18-a719-42b1-8a37-c9e58b0edf5a
    skaffold.dev/tag-policy: git-commit
  name: entry-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: entry-service
  template:
    metadata:
      labels:
        app: entry-service
        app.kubernetes.io/managed-by: skaffold-v1.12.0
        skaffold.dev/builder: local
        skaffold.dev/cleanup: "true"
        skaffold.dev/deployer: kustomize
        skaffold.dev/docker-api-version: "1.40"
        skaffold.dev/run-id: f7c22f18-a719-42b1-8a37-c9e58b0edf5a
        skaffold.dev/tag-policy: git-commit
    spec:
      containers:
      - image: registry.gitlab.com/bombie/reboarding:4c5158a4978a6f80219cf410fa56df06e4bb85be296b923e073eee9092137fa9
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        name: entry-service
        ports:
        - containerPort: 8080
        readinessProbe:
          failureThreshold: 1
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          periodSeconds: 5
        resources:
          limits:
            cpu: 4000m
            memory: 512M
          requests:
            cpu: 1000m
            memory: 256M
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: exit-service
    app.kubernetes.io/managed-by: skaffold-v1.12.0
    skaffold.dev/builder: local
    skaffold.dev/cleanup: "true"
    skaffold.dev/deployer: kustomize
    skaffold.dev/docker-api-version: "1.40"
    skaffold.dev/run-id: f7c22f18-a719-42b1-8a37-c9e58b0edf5a
    skaffold.dev/tag-policy: git-commit
  name: exit-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exit-service
  template:
    metadata:
      labels:
        app: exit-service
        app.kubernetes.io/managed-by: skaffold-v1.12.0
        skaffold.dev/builder: local
        skaffold.dev/cleanup: "true"
        skaffold.dev/deployer: kustomize
        skaffold.dev/docker-api-version: "1.40"
        skaffold.dev/run-id: f7c22f18-a719-42b1-8a37-c9e58b0edf5a
        skaffold.dev/tag-policy: git-commit
    spec:
      containers:
      - image: registry.gitlab.com/bombie/reboarding:4c5158a4978a6f80219cf410fa56df06e4bb85be296b923e073eee9092137fa9
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        name: exit-service
        ports:
        - containerPort: 8080
        readinessProbe:
          failureThreshold: 1
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          periodSeconds: 5
        resources:
          limits:
            cpu: 4000m
            memory: 512M
          requests:
            cpu: 1000m
            memory: 256M
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: registration-service
    app.kubernetes.io/managed-by: skaffold-v1.12.0
    skaffold.dev/builder: local
    skaffold.dev/cleanup: "true"
    skaffold.dev/deployer: kustomize
    skaffold.dev/docker-api-version: "1.40"
    skaffold.dev/run-id: f7c22f18-a719-42b1-8a37-c9e58b0edf5a
    skaffold.dev/tag-policy: git-commit
  name: registration-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registration-service
  template:
    metadata:
      labels:
        app: registration-service
        app.kubernetes.io/managed-by: skaffold-v1.12.0
        skaffold.dev/builder: local
        skaffold.dev/cleanup: "true"
        skaffold.dev/deployer: kustomize
        skaffold.dev/docker-api-version: "1.40"
        skaffold.dev/run-id: f7c22f18-a719-42b1-8a37-c9e58b0edf5a
        skaffold.dev/tag-policy: git-commit
    spec:
      containers:
      - image: registry.gitlab.com/bombie/reboarding:4c5158a4978a6f80219cf410fa56df06e4bb85be296b923e073eee9092137fa9
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        name: registration-service
        ports:
        - containerPort: 8080
        readinessProbe:
          failureThreshold: 1
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          periodSeconds: 5
        resources:
          limits:
            cpu: 4000m
            memory: 512M
          requests:
            cpu: 1000m
            memory: 256M
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: status-service
    app.kubernetes.io/managed-by: skaffold-v1.12.0
    skaffold.dev/builder: local
    skaffold.dev/cleanup: "true"
    skaffold.dev/deployer: kustomize
    skaffold.dev/docker-api-version: "1.40"
    skaffold.dev/run-id: f7c22f18-a719-42b1-8a37-c9e58b0edf5a
    skaffold.dev/tag-policy: git-commit
  name: status-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: status-service
  template:
    metadata:
      labels:
        app: status-service
        app.kubernetes.io/managed-by: skaffold-v1.12.0
        skaffold.dev/builder: local
        skaffold.dev/cleanup: "true"
        skaffold.dev/deployer: kustomize
        skaffold.dev/docker-api-version: "1.40"
        skaffold.dev/run-id: f7c22f18-a719-42b1-8a37-c9e58b0edf5a
        skaffold.dev/tag-policy: git-commit
    spec:
      containers:
      - image: registry.gitlab.com/bombie/reboarding:4c5158a4978a6f80219cf410fa56df06e4bb85be296b923e073eee9092137fa9
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        name: status-service
        ports:
        - containerPort: 8080
        readinessProbe:
          failureThreshold: 1
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          periodSeconds: 5
        resources:
          limits:
            cpu: 4000m
            memory: 512M
          requests:
            cpu: 1000m
            memory: 256M
