apiVersion: v1
data:
  application.properties: testvar=asdf
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/managed-by: skaffold-v1.12.0
    skaffold.dev/builder: local
    skaffold.dev/cleanup: "true"
    skaffold.dev/deployer: kustomize
    skaffold.dev/docker-api-version: "1.40"
    skaffold.dev/profile.0: qa
    skaffold.dev/run-id: 932270c9-0616-4cf3-a94d-92c84aeca607
    skaffold.dev/tag-policy: git-commit
  name: qa-config-k74gd694tf
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/managed-by: skaffold-v1.12.0
    skaffold.dev/builder: local
    skaffold.dev/cleanup: "true"
    skaffold.dev/deployer: kustomize
    skaffold.dev/docker-api-version: "1.40"
    skaffold.dev/profile.0: qa
    skaffold.dev/run-id: 932270c9-0616-4cf3-a94d-92c84aeca607
    skaffold.dev/tag-policy: git-commit
  name: api-gateway
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: api-gateway
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api-gateway
    app.kubernetes.io/managed-by: skaffold-v1.12.0
    skaffold.dev/builder: local
    skaffold.dev/cleanup: "true"
    skaffold.dev/deployer: kustomize
    skaffold.dev/docker-api-version: "1.40"
    skaffold.dev/profile.0: qa
    skaffold.dev/run-id: 932270c9-0616-4cf3-a94d-92c84aeca607
    skaffold.dev/tag-policy: git-commit
  name: api-gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
        app.kubernetes.io/managed-by: skaffold-v1.12.0
        skaffold.dev/builder: local
        skaffold.dev/cleanup: "true"
        skaffold.dev/deployer: kustomize
        skaffold.dev/docker-api-version: "1.40"
        skaffold.dev/profile.0: qa
        skaffold.dev/run-id: 932270c9-0616-4cf3-a94d-92c84aeca607
        skaffold.dev/tag-policy: git-commit
    spec:
      containers:
      - args:
        - --spring.config.location=/etc/config/application.properties
        image: registry.gitlab.com/bombie/reboarding:fb782f7662435a6f11608e6095862ccf0abec302361a65b57e7b7315ced0f89c
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        name: api-gateway
        ports:
        - containerPort: 8080
        readinessProbe:
          failureThreshold: 1
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          periodSeconds: 5
        resources:
          limits:
            cpu: 4000m
            memory: 512M
          requests:
            cpu: 1000m
            memory: 256M
        volumeMounts:
        - mountPath: /etc/config
          name: config
      volumes:
      - configMap:
          name: qa-config-k74gd694tf
        name: config
