apiVersion: v1
kind: Service
metadata:
  name: entry-request-handler
spec:
  selector:
    app: entry-request-handler
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: entry-request-handler
  name: entry-request-handler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: entry-request-handler
  template:
    metadata:
      labels:
        app: entry-request-handler
    spec:
      containers:
        - image: registry.gitlab.com/bombie/reboarding:entry-request-handler
          name: entry-request-handler
          resources:
            requests:
              memory: 256M
              cpu: 1000m
            limits:
              memory: 512M
              cpu: 4000m
          ports:
            - containerPort: 8080
          livenessProbe:
            initialDelaySeconds: 5
            periodSeconds: 5
            httpGet:
              path: /actuator/health/liveness
              port: 8080
          readinessProbe:
            periodSeconds: 5
            failureThreshold: 1
            httpGet:
              path: /actuator/health/readiness
              port: 8080
