apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - api-gateway.yaml
  - entry-request-handler.yaml
  - registration-service.yaml
  - status-service.yaml
  - entry-service.yaml
  - exit-service.yaml
