apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  template:
    spec:
      volumes:
        - name: config
          configMap:
            name: api-gateway
      containers:
        - name: api-gateway
          args:
            - --spring.config.location=/etc/config/application.properties
          volumeMounts:
            - mountPath: /etc/config
              name: config
